---
title: "DMCS Vessel Trip Report"
format: revealjs
editor: visual
---

# Number of Trips per Month

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(lubridate)

fp <- read_excel("Downloads/Digital Log of Float Plans (3).xlsx")

fp_mo_sum = fp %>% 
  mutate(date = as.POSIXct(`Date of Departure`), mo = month(date)) %>%
  group_by(mo) %>% 
  summarise(n=n())

ggplot(data = fp_mo_sum, aes(x = mo, y = n)) + 
  geom_bar(stat="identity", fill="cornflowerblue") + 
  geom_text(aes(label = n), color = "black",size = 8, vjust = -0.2)+
  labs(x = "Month", y = "Number per Month") + 
  ylim(c(0, max(fp_mo_sum$n)+1))+
  theme_bw() + 
  theme(text = element_text(size=20))
```

# Number of Trips per Vessel

```{r}
fp_sum = fp %>% group_by(`Vessel Used`) %>% summarise(n=n())

ggplot(data = fp_sum, aes(y = reorder(`Vessel Used`, n), x = n)) + 
  geom_bar(stat="identity", fill="cornflowerblue") + 
  geom_text(aes(label = n), color = "black",
            size = 6, hjust = -0.2)+
  labs(y = "Vessel", x = "Number of Trips") + 
  theme_bw() + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.6),
        text = element_text(size=20)) + 
  xlim(c(0, max(fp_sum$n)+1))
```

# Operations

```{r}
fp_sum = fp %>% group_by(Operations) %>% summarise(n=n())

ggplot(data = fp_sum, aes(y = reorder(Operations, n), x = n)) + 
  geom_bar(stat="identity", fill="cornflowerblue") + 
  geom_text(aes(label = n), color = "black",
            size = 6, hjust = -0.2)+
  labs(y = "Operations", x = "Number of Trips") + 
  theme_bw() + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.6),
        text = element_text(size=20)) + 
  xlim(c(0, max(fp_sum$n)+1))
```


