---
title: "Vessel Trip Report October 2025"
format: revealjs
editor: visual
---

## Number of Trips per Month

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(lubridate)
library(gridExtra)

fp <- read_excel("~/Downloads/Digital Log of Float Plans (15).xlsx")

fp_mo_sum = fp %>% 
  mutate(date = as.POSIXct(`Date of Departure`), mo = month(date)) %>%
  group_by(mo) %>% 
  summarise(n=n())

ggplot(data = fp_mo_sum, aes(x = mo, y = n)) + 
  geom_bar(stat="identity", fill="cornflowerblue") + 
  geom_text(aes(label = n), color = "black",size = 8, vjust = -0.2)+
  labs(x = "Month", y = "Number per Month") + 
  ylim(c(0, max(fp_mo_sum$n)+1))+
  scale_x_continuous(breaks = seq(1, max(fp_mo_sum$mo), 1)) +
  theme_bw() + 
  theme(text = element_text(size=20))
```

## Number of Trips per Vessel

```{r}
fp_sum = fp %>% group_by(`Vessel Used`) %>% 
  summarise(n=n()) %>% 
  mutate(group = ifelse(`Vessel Used` %in% c("Soggy Bottom","RV Rutgers",
                                             "Mullica Explorer", "RV Arabella",
                                             "Carolina Skiff", "RV Resilience"),
                        "Rutgers","Other"),
         group = ifelse(`Vessel Used` %in% c("RV William R Mote","RV Eugenie Clark"), 
                        "MOTE", group),
         group = ifelse(`Vessel Used` %in% c("RV Neal Armstrong"),"WHOI", group),
         group = ifelse(grepl("SeaTow", `Vessel Used`), "SeaTow/TowBoat", group),
         group = ifelse(grepl("TowBoat", `Vessel Used`), "SeaTow/TowBoat", group),
         group = ifelse(`Vessel Used` %in% c("RV Joanne Daiber", "RV Sea Regalis"), 
                        "UDel", group),
         group = ifelse(`Vessel Used` %in% c("zodiac", "RHIB Hadar"), 
                        "Palmer", group),
         group = ifelse(grepl("FV", `Vessel Used`), "FV", group))

p1 = ggplot(data = fp_sum, aes(y = reorder(`Vessel Used`, n), x = n)) + 
  geom_bar(stat="identity", aes(fill=group)) + 
  geom_text(aes(label = n), color = "black",
            size = 3, hjust = -0.2)+
  labs(y = "Vessel", x = "Number of Trips") + 
  theme_bw() + 
  #theme(text = element_text(size=15)) + 
  xlim(c(0, max(fp_sum$n)+1)) + 
  theme(legend.position = "none") +
  scale_fill_manual("Legend", 
                    values = c("Rutgers" = "#CC6677", "MOTE" = "#DDCC77",
                               "UDel" = "#888888", "Other" = "#332288",
                               "FV" = "#88CCEE", "SeaTow/TowBoat" = "#999933",
                               "WHOI" = "#44AA99", "Palmer" = "#661100"))

fp_sum2 = fp_sum %>% 
  group_by(group) %>% 
  summarise(n2 = sum(n)) 

p2 = ggplot(data = fp_sum2, aes(x = reorder(group, n2), y = n2)) + 
  geom_bar(stat="identity", aes(fill=group))+ 
  labs(x = "Vessel Group", y = "Number of Trips") + 
  geom_text(aes(label = n2), color = "black",
            size = 3, vjust = -0.2)+
  theme_bw() + 
  theme(text = element_text(size=10),
        axis.text.x = element_text(angle = 65, vjust = 0.5, hjust = 0.5)) + 
  scale_fill_manual("Legend", 
                    values = c("Rutgers" = "#CC6677", "MOTE" = "#DDCC77",
                               "UDel" = "#888888", "Other" = "#332288",
                               "FV" = "#88CCEE", "SeaTow/TowBoat" = "#999933",
                               "WHOI" = "#44AA99", "Palmer" = "#661100"))
grid.arrange(p1, p2, ncol= 2, widths = c(1.8, 1.2))
#https://stackoverflow.com/questions/57153428/r-plot-color-combinations-that-are-colorblind-accessible
```

## Operations

```{r}
fp_sum = fp %>% group_by(Operations) %>% 
  summarise(n=n()) %>% 
  mutate(group = ifelse(Operations %in% c("Gliders", "Gliders, Net Tows",
                                          "Glider, Jaia Bot",
                                          "Diving","MOCNESS, FOSI camera, Wirewalker, sediment trap", 
                                          "Rock Hoppers","Dye experiment"),
                        "DMCS",
                        ifelse(Operations %in% 
                                        c("Facilities Maintenance","Class"), 
                                      "Mixed","RUMFS/JCNEER")),
         group = ifelse(Operations %in% c("Dredge"), "HSRL",group),
                        Operations = ifelse(Operations %in% "Facilities Maintenance",
                             "Facilities/Vessel Maintenance",Operations))

ggplot(data = fp_sum, aes(y = reorder(Operations, n), x = n)) + 
  geom_bar(stat="identity", aes(fill=group)) + 
  geom_text(aes(label = n), color = "black",
            size = 4, hjust = -0.2)+
  labs(y = "Operations", x = "Number of Trips") + 
  theme_bw() + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.6),
        text = element_text(size=12)) + 
  xlim(c(0, max(fp_sum$n)+1))+ 
  scale_fill_manual("Legend", values = c("DMCS" = "gold", 
                                         "HSRL" = "#332288",
                                         "Mixed" = "grey", 
                                         "RUMFS/JCNEER" = "cornflowerblue"))
```

## Incident Logs

```{r}
library(readxl)
library(dplyr)
library(knitr)
library(tidyverse)
library(kableExtra)

il <- read_excel("~/Downloads/RU Marine Ops HSE Records (2).xlsx", 
                 sheet=1, skip=1)
il = filter(il, Status %in% "Open") %>% 
  select(!`ASOW Status Categories`)
  
kbl_table = kbl(il, format.args = list(big.mark = ",")) %>%
  kable_styling(font_size = 15)

#highlight_rows <- which(il[,13] == "Closed")

kbl_table %>%
      #row_spec(row = highlight_rows, background = "darkseagreen1") %>%
      row_spec(row = 0, color = "darkorchid4", background = "thistle2") 
```
